### ISSUE TITLE
TypedArray Polyfill fails when implemented

### ISSUE THREAD

**Issue by Tokimon** [zloirock/core-js#379]
When add the `es6/typed.js` polyfill it throws the following error, that makes everything else on the page break:

```
Uncaught TypeError: Function.prototype.toString requires that 'this' be a Function
```

Which stems from the `$toString.call(this)` in this line in `modules/_redefine.js` (used by `modules/es6.object.to-string.js`):

```js
// add fake Function#toString for correct work wrapped methods / constructors with methods like LoDash isNative
})(Function.prototype, TO_STRING, function toString() {
  return typeof this == 'function' && this[SRC] || $toString.call(this);
});
```

**Comment by zloirock** [comment]
This issue was fixed in actual `core-js` versions. Could you check your version?

**Comment by Tokimon** [comment]
ok thanks. I will check

**Comment by Tokimon** [comment]
I just verified that I have the latest version (2.5.3) and I still have the issue

**Comment by zloirock** [comment]
In this case, please, add a reproducible example.

**Comment by Tokimon** [comment]
ok I will look into it.

**Comment by zloirock** [comment]
Closed as `can't reproduce`. Most likely you load some versions of `core-js` and one of them without fixing this problem.
